%%% This file was automatically generated by snmpc_mib_to_hrl version 4.22.1
%%% Date: 20-Nov-2012::14:49:55
-ifndef('PowerNet-MIB').
-define('PowerNet-MIB', true).

%% Oids

-define(apc, [1,3,6,1,4,1,318]).

-define(products, [1,3,6,1,4,1,318,1]).

-define(hardware, [1,3,6,1,4,1,318,1,1]).

-define(ups, [1,3,6,1,4,1,318,1,1,1]).

-define(upsIdent, [1,3,6,1,4,1,318,1,1,1,1]).

-define(upsBasicIdent, [1,3,6,1,4,1,318,1,1,1,1,1]).
-define(upsBasicIdentModel, [1,3,6,1,4,1,318,1,1,1,1,1,1]).
-define(upsBasicIdentModel_instance, [1,3,6,1,4,1,318,1,1,1,1,1,1,0]).
-define(upsBasicIdentName, [1,3,6,1,4,1,318,1,1,1,1,1,2]).
-define(upsBasicIdentName_instance, [1,3,6,1,4,1,318,1,1,1,1,1,2,0]).

-define(upsAdvIdent, [1,3,6,1,4,1,318,1,1,1,1,2]).
-define(upsAdvIdentFirmwareRevision, [1,3,6,1,4,1,318,1,1,1,1,2,1]).
-define(upsAdvIdentFirmwareRevision_instance, [1,3,6,1,4,1,318,1,1,1,1,2,1,0]).
-define(upsAdvIdentDateOfManufacture, [1,3,6,1,4,1,318,1,1,1,1,2,2]).
-define(upsAdvIdentDateOfManufacture_instance, [1,3,6,1,4,1,318,1,1,1,1,2,2,0]).
-define(upsAdvIdentSerialNumber, [1,3,6,1,4,1,318,1,1,1,1,2,3]).
-define(upsAdvIdentSerialNumber_instance, [1,3,6,1,4,1,318,1,1,1,1,2,3,0]).
-define(upsAdvIdentFirmwareRevision2, [1,3,6,1,4,1,318,1,1,1,1,2,4]).
-define(upsAdvIdentFirmwareRevision2_instance, [1,3,6,1,4,1,318,1,1,1,1,2,4,0]).
-define(upsAdvIdentSkuNumber, [1,3,6,1,4,1,318,1,1,1,1,2,5]).
-define(upsAdvIdentSkuNumber_instance, [1,3,6,1,4,1,318,1,1,1,1,2,5,0]).

-define(upsBattery, [1,3,6,1,4,1,318,1,1,1,2]).

-define(upsBasicBattery, [1,3,6,1,4,1,318,1,1,1,2,1]).
-define(upsBasicBatteryStatus, [1,3,6,1,4,1,318,1,1,1,2,1,1]).
-define(upsBasicBatteryStatus_instance, [1,3,6,1,4,1,318,1,1,1,2,1,1,0]).
-define(upsBasicBatteryTimeOnBattery, [1,3,6,1,4,1,318,1,1,1,2,1,2]).
-define(upsBasicBatteryTimeOnBattery_instance, [1,3,6,1,4,1,318,1,1,1,2,1,2,0]).
-define(upsBasicBatteryLastReplaceDate, [1,3,6,1,4,1,318,1,1,1,2,1,3]).
-define(upsBasicBatteryLastReplaceDate_instance, [1,3,6,1,4,1,318,1,1,1,2,1,3,0]).

-define(upsAdvBattery, [1,3,6,1,4,1,318,1,1,1,2,2]).
-define(upsAdvBatteryCapacity, [1,3,6,1,4,1,318,1,1,1,2,2,1]).
-define(upsAdvBatteryCapacity_instance, [1,3,6,1,4,1,318,1,1,1,2,2,1,0]).
-define(upsAdvBatteryTemperature, [1,3,6,1,4,1,318,1,1,1,2,2,2]).
-define(upsAdvBatteryTemperature_instance, [1,3,6,1,4,1,318,1,1,1,2,2,2,0]).
-define(upsAdvBatteryRunTimeRemaining, [1,3,6,1,4,1,318,1,1,1,2,2,3]).
-define(upsAdvBatteryRunTimeRemaining_instance, [1,3,6,1,4,1,318,1,1,1,2,2,3,0]).
-define(upsAdvBatteryReplaceIndicator, [1,3,6,1,4,1,318,1,1,1,2,2,4]).
-define(upsAdvBatteryReplaceIndicator_instance, [1,3,6,1,4,1,318,1,1,1,2,2,4,0]).
-define(upsAdvBatteryNumOfBattPacks, [1,3,6,1,4,1,318,1,1,1,2,2,5]).
-define(upsAdvBatteryNumOfBattPacks_instance, [1,3,6,1,4,1,318,1,1,1,2,2,5,0]).
-define(upsAdvBatteryNumOfBadBattPacks, [1,3,6,1,4,1,318,1,1,1,2,2,6]).
-define(upsAdvBatteryNumOfBadBattPacks_instance, [1,3,6,1,4,1,318,1,1,1,2,2,6,0]).
-define(upsAdvBatteryNominalVoltage, [1,3,6,1,4,1,318,1,1,1,2,2,7]).
-define(upsAdvBatteryNominalVoltage_instance, [1,3,6,1,4,1,318,1,1,1,2,2,7,0]).
-define(upsAdvBatteryActualVoltage, [1,3,6,1,4,1,318,1,1,1,2,2,8]).
-define(upsAdvBatteryActualVoltage_instance, [1,3,6,1,4,1,318,1,1,1,2,2,8,0]).
-define(upsAdvBatteryCurrent, [1,3,6,1,4,1,318,1,1,1,2,2,9]).
-define(upsAdvBatteryCurrent_instance, [1,3,6,1,4,1,318,1,1,1,2,2,9,0]).
-define(upsAdvTotalDCCurrent, [1,3,6,1,4,1,318,1,1,1,2,2,10]).
-define(upsAdvTotalDCCurrent_instance, [1,3,6,1,4,1,318,1,1,1,2,2,10,0]).
-define(upsAdvBatteryFullCapacity, [1,3,6,1,4,1,318,1,1,1,2,2,11]).
-define(upsAdvBatteryFullCapacity_instance, [1,3,6,1,4,1,318,1,1,1,2,2,11,0]).

-define(upsAdvBatteryActualVoltageTable, [1,3,6,1,4,1,318,1,1,1,2,2,12]).

-define(upsAdvBatteryActualVoltageEntry, [1,3,6,1,4,1,318,1,1,1,2,2,12,1]).
-define(upsAdvBatteryActualVoltageTableIndex, 1).
-define(upsAdvBatteryActualVoltagePolarity, 2).
-define(upsAdvBatteryFrameActualVoltage, 3).

-define(upsAdvTotalDCCurrentTable, [1,3,6,1,4,1,318,1,1,1,2,2,13]).

-define(upsAdvTotalDCCurrentEntry, [1,3,6,1,4,1,318,1,1,1,2,2,13,1]).
-define(upsAdvTotalDCCurrentTableIndex, 1).
-define(upsAdvTotalDCCurrentPolarity, 2).
-define(upsAdvTotalFrameDCCurrent, 3).

-define(upsAdvBatteryCurrentTable, [1,3,6,1,4,1,318,1,1,1,2,2,14]).

-define(upsAdvBatteryCurrentEntry, [1,3,6,1,4,1,318,1,1,1,2,2,14,1]).
-define(upsAdvBatteryCurrentTableIndex, 1).
-define(upsAdvBatteryCurrentIndex, 2).
-define(upsAdvBatteryCurrentPolarity, 3).
-define(upsAdvBatteryFrameCurrent, 4).

-define(upsHighPrecBattery, [1,3,6,1,4,1,318,1,1,1,2,3]).
-define(upsHighPrecBatteryCapacity, [1,3,6,1,4,1,318,1,1,1,2,3,1]).
-define(upsHighPrecBatteryCapacity_instance, [1,3,6,1,4,1,318,1,1,1,2,3,1,0]).
-define(upsHighPrecBatteryTemperature, [1,3,6,1,4,1,318,1,1,1,2,3,2]).
-define(upsHighPrecBatteryTemperature_instance, [1,3,6,1,4,1,318,1,1,1,2,3,2,0]).
-define(upsHighPrecBatteryNominalVoltage, [1,3,6,1,4,1,318,1,1,1,2,3,3]).
-define(upsHighPrecBatteryNominalVoltage_instance, [1,3,6,1,4,1,318,1,1,1,2,3,3,0]).
-define(upsHighPrecBatteryActualVoltage, [1,3,6,1,4,1,318,1,1,1,2,3,4]).
-define(upsHighPrecBatteryActualVoltage_instance, [1,3,6,1,4,1,318,1,1,1,2,3,4,0]).
-define(upsHighPrecBatteryCurrent, [1,3,6,1,4,1,318,1,1,1,2,3,5]).
-define(upsHighPrecBatteryCurrent_instance, [1,3,6,1,4,1,318,1,1,1,2,3,5,0]).
-define(upsHighPrecTotalDCCurrent, [1,3,6,1,4,1,318,1,1,1,2,3,6]).
-define(upsHighPrecTotalDCCurrent_instance, [1,3,6,1,4,1,318,1,1,1,2,3,6,0]).

-define(upsHighPrecBatteryActualVoltageTable, [1,3,6,1,4,1,318,1,1,1,2,3,7]).

-define(upsHighPrecBatteryActualVoltageEntry, [1,3,6,1,4,1,318,1,1,1,2,3,7,1]).
-define(upsHighPrecBatteryActualVoltageTableIndex, 1).
-define(upsHighPrecBatteryActualVoltagePolarity, 2).
-define(upsHighPrecBatteryVoltage, 3).

-define(upsHighPrecTotalDCCurrentTable, [1,3,6,1,4,1,318,1,1,1,2,3,8]).

-define(upsHighPrecTotalDCCurrentEntry, [1,3,6,1,4,1,318,1,1,1,2,3,8,1]).
-define(upsHighPrecTotalDCCurrentTableIndex, 1).
-define(upsHighPrecTotalDCCurrentPolarity, 2).
-define(upsHighPrecTotalDCFrameCurrent, 3).

-define(upsHighPrecBatteryCurrentTable, [1,3,6,1,4,1,318,1,1,1,2,3,9]).

-define(upsHighPrecBatteryCurrentEntry, [1,3,6,1,4,1,318,1,1,1,2,3,9,1]).
-define(upsHighPrecBatteryCurrentTableIndex, 1).
-define(upsHighPrecBatteryCurrentIndex, 2).
-define(upsHighPrecBatteryCurrentPolarity, 3).
-define(upsHighPrecBatteryFrameCurrent, 4).

-define(upsInput, [1,3,6,1,4,1,318,1,1,1,3]).

-define(upsBasicInput, [1,3,6,1,4,1,318,1,1,1,3,1]).
-define(upsBasicInputPhase, [1,3,6,1,4,1,318,1,1,1,3,1,1]).
-define(upsBasicInputPhase_instance, [1,3,6,1,4,1,318,1,1,1,3,1,1,0]).

-define(upsAdvInput, [1,3,6,1,4,1,318,1,1,1,3,2]).
-define(upsAdvInputLineVoltage, [1,3,6,1,4,1,318,1,1,1,3,2,1]).
-define(upsAdvInputLineVoltage_instance, [1,3,6,1,4,1,318,1,1,1,3,2,1,0]).
-define(upsAdvInputMaxLineVoltage, [1,3,6,1,4,1,318,1,1,1,3,2,2]).
-define(upsAdvInputMaxLineVoltage_instance, [1,3,6,1,4,1,318,1,1,1,3,2,2,0]).
-define(upsAdvInputMinLineVoltage, [1,3,6,1,4,1,318,1,1,1,3,2,3]).
-define(upsAdvInputMinLineVoltage_instance, [1,3,6,1,4,1,318,1,1,1,3,2,3,0]).
-define(upsAdvInputFrequency, [1,3,6,1,4,1,318,1,1,1,3,2,4]).
-define(upsAdvInputFrequency_instance, [1,3,6,1,4,1,318,1,1,1,3,2,4,0]).
-define(upsAdvInputLineFailCause, [1,3,6,1,4,1,318,1,1,1,3,2,5]).
-define(upsAdvInputLineFailCause_instance, [1,3,6,1,4,1,318,1,1,1,3,2,5,0]).
-define(upsAdvInputNominalFrequency, [1,3,6,1,4,1,318,1,1,1,3,2,6]).
-define(upsAdvInputNominalFrequency_instance, [1,3,6,1,4,1,318,1,1,1,3,2,6,0]).
-define(upsAdvInputNominalVoltage, [1,3,6,1,4,1,318,1,1,1,3,2,7]).
-define(upsAdvInputNominalVoltage_instance, [1,3,6,1,4,1,318,1,1,1,3,2,7,0]).
-define(upsAdvInputBypassNominalFrequency, [1,3,6,1,4,1,318,1,1,1,3,2,8]).
-define(upsAdvInputBypassNominalFrequency_instance, [1,3,6,1,4,1,318,1,1,1,3,2,8,0]).
-define(upsAdvInputBypassNominalVoltage, [1,3,6,1,4,1,318,1,1,1,3,2,9]).
-define(upsAdvInputBypassNominalVoltage_instance, [1,3,6,1,4,1,318,1,1,1,3,2,9,0]).

-define(upsAdvInputStatisticsTable, [1,3,6,1,4,1,318,1,1,1,3,2,10]).

-define(upsAdvInputStatisticsEntry, [1,3,6,1,4,1,318,1,1,1,3,2,10,1]).
-define(upsAdvInputStatisticsIndex, 1).
-define(upsAdvInputApparentPower, 2).
-define(upsAdvInputVoltageTHD, 3).
-define(upsAdvInputBypassVoltageTHD, 4).
-define(upsAdvInputPeakCurrent, 5).
-define(upsAdvInputBypassPeakCurrent, 6).

-define(upsHighPrecInput, [1,3,6,1,4,1,318,1,1,1,3,3]).
-define(upsHighPrecInputLineVoltage, [1,3,6,1,4,1,318,1,1,1,3,3,1]).
-define(upsHighPrecInputLineVoltage_instance, [1,3,6,1,4,1,318,1,1,1,3,3,1,0]).
-define(upsHighPrecInputMaxLineVoltage, [1,3,6,1,4,1,318,1,1,1,3,3,2]).
-define(upsHighPrecInputMaxLineVoltage_instance, [1,3,6,1,4,1,318,1,1,1,3,3,2,0]).
-define(upsHighPrecInputMinLineVoltage, [1,3,6,1,4,1,318,1,1,1,3,3,3]).
-define(upsHighPrecInputMinLineVoltage_instance, [1,3,6,1,4,1,318,1,1,1,3,3,3,0]).
-define(upsHighPrecInputFrequency, [1,3,6,1,4,1,318,1,1,1,3,3,4]).
-define(upsHighPrecInputFrequency_instance, [1,3,6,1,4,1,318,1,1,1,3,3,4,0]).

-define(upsOutput, [1,3,6,1,4,1,318,1,1,1,4]).

-define(upsBasicOutput, [1,3,6,1,4,1,318,1,1,1,4,1]).
-define(upsBasicOutputStatus, [1,3,6,1,4,1,318,1,1,1,4,1,1]).
-define(upsBasicOutputStatus_instance, [1,3,6,1,4,1,318,1,1,1,4,1,1,0]).
-define(upsBasicOutputPhase, [1,3,6,1,4,1,318,1,1,1,4,1,2]).
-define(upsBasicOutputPhase_instance, [1,3,6,1,4,1,318,1,1,1,4,1,2,0]).
-define(upsBasicSystemStatus, [1,3,6,1,4,1,318,1,1,1,4,1,3]).
-define(upsBasicSystemStatus_instance, [1,3,6,1,4,1,318,1,1,1,4,1,3,0]).
-define(upsBasicSystemInternalTemperature, [1,3,6,1,4,1,318,1,1,1,4,1,4]).
-define(upsBasicSystemInternalTemperature_instance, [1,3,6,1,4,1,318,1,1,1,4,1,4,0]).

-define(upsAdvOutput, [1,3,6,1,4,1,318,1,1,1,4,2]).
-define(upsAdvOutputVoltage, [1,3,6,1,4,1,318,1,1,1,4,2,1]).
-define(upsAdvOutputVoltage_instance, [1,3,6,1,4,1,318,1,1,1,4,2,1,0]).
-define(upsAdvOutputFrequency, [1,3,6,1,4,1,318,1,1,1,4,2,2]).
-define(upsAdvOutputFrequency_instance, [1,3,6,1,4,1,318,1,1,1,4,2,2,0]).
-define(upsAdvOutputLoad, [1,3,6,1,4,1,318,1,1,1,4,2,3]).
-define(upsAdvOutputLoad_instance, [1,3,6,1,4,1,318,1,1,1,4,2,3,0]).
-define(upsAdvOutputCurrent, [1,3,6,1,4,1,318,1,1,1,4,2,4]).
-define(upsAdvOutputCurrent_instance, [1,3,6,1,4,1,318,1,1,1,4,2,4,0]).
-define(upsAdvOutputRedundancy, [1,3,6,1,4,1,318,1,1,1,4,2,5]).
-define(upsAdvOutputRedundancy_instance, [1,3,6,1,4,1,318,1,1,1,4,2,5,0]).
-define(upsAdvOutputKVACapacity, [1,3,6,1,4,1,318,1,1,1,4,2,6]).
-define(upsAdvOutputKVACapacity_instance, [1,3,6,1,4,1,318,1,1,1,4,2,6,0]).
-define(upsAdvOutputNominalFrequency, [1,3,6,1,4,1,318,1,1,1,4,2,7]).
-define(upsAdvOutputNominalFrequency_instance, [1,3,6,1,4,1,318,1,1,1,4,2,7,0]).
-define(upsAdvOutputActivePower, [1,3,6,1,4,1,318,1,1,1,4,2,8]).
-define(upsAdvOutputActivePower_instance, [1,3,6,1,4,1,318,1,1,1,4,2,8,0]).
-define(upsAdvOutputApparentPower, [1,3,6,1,4,1,318,1,1,1,4,2,9]).
-define(upsAdvOutputApparentPower_instance, [1,3,6,1,4,1,318,1,1,1,4,2,9,0]).

-define(upsAdvOutputStatisticsTable, [1,3,6,1,4,1,318,1,1,1,4,2,10]).

-define(upsAdvOutputStatisticsEntry, [1,3,6,1,4,1,318,1,1,1,4,2,10,1]).
-define(upsAdvOutputStatisticsIndex, 1).
-define(upsAdvOutputPeakCurrent, 2).
-define(upsAdvOutputCurrentTHD, 3).
-define(upsAdvOutputCrestFactor, 4).

-define(upsHighPrecOutput, [1,3,6,1,4,1,318,1,1,1,4,3]).
-define(upsHighPrecOutputVoltage, [1,3,6,1,4,1,318,1,1,1,4,3,1]).
-define(upsHighPrecOutputVoltage_instance, [1,3,6,1,4,1,318,1,1,1,4,3,1,0]).
-define(upsHighPrecOutputFrequency, [1,3,6,1,4,1,318,1,1,1,4,3,2]).
-define(upsHighPrecOutputFrequency_instance, [1,3,6,1,4,1,318,1,1,1,4,3,2,0]).
-define(upsHighPrecOutputLoad, [1,3,6,1,4,1,318,1,1,1,4,3,3]).
-define(upsHighPrecOutputLoad_instance, [1,3,6,1,4,1,318,1,1,1,4,3,3,0]).
-define(upsHighPrecOutputCurrent, [1,3,6,1,4,1,318,1,1,1,4,3,4]).
-define(upsHighPrecOutputCurrent_instance, [1,3,6,1,4,1,318,1,1,1,4,3,4,0]).
-define(upsHighPrecOutputEfficiency, [1,3,6,1,4,1,318,1,1,1,4,3,5]).
-define(upsHighPrecOutputEfficiency_instance, [1,3,6,1,4,1,318,1,1,1,4,3,5,0]).
-define(upsHighPrecOutputEnergyUsage, [1,3,6,1,4,1,318,1,1,1,4,3,6]).
-define(upsHighPrecOutputEnergyUsage_instance, [1,3,6,1,4,1,318,1,1,1,4,3,6,0]).

-define(upsConfig, [1,3,6,1,4,1,318,1,1,1,5]).

-define(upsBasicConfig, [1,3,6,1,4,1,318,1,1,1,5,1]).
-define(upsBasicConfigNumDevices, [1,3,6,1,4,1,318,1,1,1,5,1,1]).
-define(upsBasicConfigNumDevices_instance, [1,3,6,1,4,1,318,1,1,1,5,1,1,0]).

-define(upsBasicConfigDeviceTable, [1,3,6,1,4,1,318,1,1,1,5,1,2]).

-define(upsBasicConfigDeviceEntry, [1,3,6,1,4,1,318,1,1,1,5,1,2,1]).
-define(deviceIndex, 1).
-define(deviceName, 2).
-define(vaRating, 3).
-define(acceptThisDevice, 4).

-define(upsAdvConfig, [1,3,6,1,4,1,318,1,1,1,5,2]).
-define(upsAdvConfigRatedOutputVoltage, [1,3,6,1,4,1,318,1,1,1,5,2,1]).
-define(upsAdvConfigRatedOutputVoltage_instance, [1,3,6,1,4,1,318,1,1,1,5,2,1,0]).
-define(upsAdvConfigHighTransferVolt, [1,3,6,1,4,1,318,1,1,1,5,2,2]).
-define(upsAdvConfigHighTransferVolt_instance, [1,3,6,1,4,1,318,1,1,1,5,2,2,0]).
-define(upsAdvConfigLowTransferVolt, [1,3,6,1,4,1,318,1,1,1,5,2,3]).
-define(upsAdvConfigLowTransferVolt_instance, [1,3,6,1,4,1,318,1,1,1,5,2,3,0]).
-define(upsAdvConfigAlarm, [1,3,6,1,4,1,318,1,1,1,5,2,4]).
-define(upsAdvConfigAlarm_instance, [1,3,6,1,4,1,318,1,1,1,5,2,4,0]).
-define(upsAdvConfigAlarmTimer, [1,3,6,1,4,1,318,1,1,1,5,2,5]).
-define(upsAdvConfigAlarmTimer_instance, [1,3,6,1,4,1,318,1,1,1,5,2,5,0]).
-define(upsAdvConfigMinReturnCapacity, [1,3,6,1,4,1,318,1,1,1,5,2,6]).
-define(upsAdvConfigMinReturnCapacity_instance, [1,3,6,1,4,1,318,1,1,1,5,2,6,0]).
-define(upsAdvConfigSensitivity, [1,3,6,1,4,1,318,1,1,1,5,2,7]).
-define(upsAdvConfigSensitivity_instance, [1,3,6,1,4,1,318,1,1,1,5,2,7,0]).
-define(upsAdvConfigLowBatteryRunTime, [1,3,6,1,4,1,318,1,1,1,5,2,8]).
-define(upsAdvConfigLowBatteryRunTime_instance, [1,3,6,1,4,1,318,1,1,1,5,2,8,0]).
-define(upsAdvConfigReturnDelay, [1,3,6,1,4,1,318,1,1,1,5,2,9]).
-define(upsAdvConfigReturnDelay_instance, [1,3,6,1,4,1,318,1,1,1,5,2,9,0]).
-define(upsAdvConfigShutoffDelay, [1,3,6,1,4,1,318,1,1,1,5,2,10]).
-define(upsAdvConfigShutoffDelay_instance, [1,3,6,1,4,1,318,1,1,1,5,2,10,0]).
-define(upsAdvConfigUpsSleepTime, [1,3,6,1,4,1,318,1,1,1,5,2,11]).
-define(upsAdvConfigUpsSleepTime_instance, [1,3,6,1,4,1,318,1,1,1,5,2,11,0]).
-define(upsAdvConfigSetEEPROMDefaults, [1,3,6,1,4,1,318,1,1,1,5,2,12]).
-define(upsAdvConfigSetEEPROMDefaults_instance, [1,3,6,1,4,1,318,1,1,1,5,2,12,0]).

-define(upsAdvConfigDipSwitchTable, [1,3,6,1,4,1,318,1,1,1,5,2,13]).

-define(upsAdvConfigDipSwitchEntry, [1,3,6,1,4,1,318,1,1,1,5,2,13,1]).
-define(dipSwitchIndex, 1).
-define(dipSwitchStatus, 2).
-define(upsAdvConfigBattExhaustThresh, [1,3,6,1,4,1,318,1,1,1,5,2,14]).
-define(upsAdvConfigBattExhaustThresh_instance, [1,3,6,1,4,1,318,1,1,1,5,2,14,0]).
-define(upsAdvConfigPassword, [1,3,6,1,4,1,318,1,1,1,5,2,15]).
-define(upsAdvConfigPassword_instance, [1,3,6,1,4,1,318,1,1,1,5,2,15,0]).

-define(upsAdvConfigAllowedSetTable, [1,3,6,1,4,1,318,1,1,1,5,2,16]).

-define(upsAdvConfigAllowedSetEntry, [1,3,6,1,4,1,318,1,1,1,5,2,16,1]).
-define(apcUpsConfigFieldIndex, 1).
-define(apcUpsConfigFieldOID, 2).
-define(apcUpsConfigFieldValueRange, 3).
-define(upsAdvConfigBattCabAmpHour, [1,3,6,1,4,1,318,1,1,1,5,2,17]).
-define(upsAdvConfigBattCabAmpHour_instance, [1,3,6,1,4,1,318,1,1,1,5,2,17,0]).
-define(upsAdvConfigPositionSelector, [1,3,6,1,4,1,318,1,1,1,5,2,18]).
-define(upsAdvConfigPositionSelector_instance, [1,3,6,1,4,1,318,1,1,1,5,2,18,0]).
-define(upsAdvConfigOutputFreqRange, [1,3,6,1,4,1,318,1,1,1,5,2,19]).
-define(upsAdvConfigOutputFreqRange_instance, [1,3,6,1,4,1,318,1,1,1,5,2,19,0]).
-define(upsAdvConfigUPSFail, [1,3,6,1,4,1,318,1,1,1,5,2,20]).
-define(upsAdvConfigUPSFail_instance, [1,3,6,1,4,1,318,1,1,1,5,2,20,0]).
-define(upsAdvConfigAlarmRedundancy, [1,3,6,1,4,1,318,1,1,1,5,2,21]).
-define(upsAdvConfigAlarmRedundancy_instance, [1,3,6,1,4,1,318,1,1,1,5,2,21,0]).
-define(upsAdvConfigAlarmLoadOver, [1,3,6,1,4,1,318,1,1,1,5,2,22]).
-define(upsAdvConfigAlarmLoadOver_instance, [1,3,6,1,4,1,318,1,1,1,5,2,22,0]).
-define(upsAdvConfigAlarmRuntimeUnder, [1,3,6,1,4,1,318,1,1,1,5,2,23]).
-define(upsAdvConfigAlarmRuntimeUnder_instance, [1,3,6,1,4,1,318,1,1,1,5,2,23,0]).
-define(upsAdvConfigVoutReporting, [1,3,6,1,4,1,318,1,1,1,5,2,24]).
-define(upsAdvConfigVoutReporting_instance, [1,3,6,1,4,1,318,1,1,1,5,2,24,0]).
-define(upsAdvConfigNumExternalBatteries, [1,3,6,1,4,1,318,1,1,1,5,2,25]).
-define(upsAdvConfigNumExternalBatteries_instance, [1,3,6,1,4,1,318,1,1,1,5,2,25,0]).
-define(upsAdvConfigSimpleSignalShutdowns, [1,3,6,1,4,1,318,1,1,1,5,2,26]).
-define(upsAdvConfigSimpleSignalShutdowns_instance, [1,3,6,1,4,1,318,1,1,1,5,2,26,0]).
-define(upsAdvConfigMaxShutdownTime, [1,3,6,1,4,1,318,1,1,1,5,2,27]).
-define(upsAdvConfigMaxShutdownTime_instance, [1,3,6,1,4,1,318,1,1,1,5,2,27,0]).
-define(upsAsiUpsControlServerRequestShutdown, [1,3,6,1,4,1,318,1,1,1,5,2,28]).
-define(upsAsiUpsControlServerRequestShutdown_instance, [1,3,6,1,4,1,318,1,1,1,5,2,28,0]).
-define(upsAdvConfigMinReturnRuntime, [1,3,6,1,4,1,318,1,1,1,5,2,29]).
-define(upsAdvConfigMinReturnRuntime_instance, [1,3,6,1,4,1,318,1,1,1,5,2,29,0]).
-define(upsAdvConfigBasicSignalLowBatteryDuration, [1,3,6,1,4,1,318,1,1,1,5,2,30]).
-define(upsAdvConfigBasicSignalLowBatteryDuration_instance, [1,3,6,1,4,1,318,1,1,1,5,2,30,0]).
-define(upsAdvConfigBypassPhaseLockRequired, [1,3,6,1,4,1,318,1,1,1,5,2,31]).
-define(upsAdvConfigBypassPhaseLockRequired_instance, [1,3,6,1,4,1,318,1,1,1,5,2,31,0]).
-define(upsAdvConfigOutputFreqSlewRate, [1,3,6,1,4,1,318,1,1,1,5,2,32]).
-define(upsAdvConfigOutputFreqSlewRate_instance, [1,3,6,1,4,1,318,1,1,1,5,2,32,0]).
-define(upsAdvConfigChargerLevel, [1,3,6,1,4,1,318,1,1,1,5,2,33]).
-define(upsAdvConfigChargerLevel_instance, [1,3,6,1,4,1,318,1,1,1,5,2,33,0]).
-define(upsAdvConfigBypassToleranceSetting, [1,3,6,1,4,1,318,1,1,1,5,2,34]).
-define(upsAdvConfigBypassToleranceSetting_instance, [1,3,6,1,4,1,318,1,1,1,5,2,34,0]).
-define(upsAdvConfigMainsSetting, [1,3,6,1,4,1,318,1,1,1,5,2,35]).
-define(upsAdvConfigMainsSetting_instance, [1,3,6,1,4,1,318,1,1,1,5,2,35,0]).
-define(upsAdvConfigACWiringSetting, [1,3,6,1,4,1,318,1,1,1,5,2,36]).
-define(upsAdvConfigACWiringSetting_instance, [1,3,6,1,4,1,318,1,1,1,5,2,36,0]).
-define(upsAdvConfigUpperOutputVoltTolerance, [1,3,6,1,4,1,318,1,1,1,5,2,37]).
-define(upsAdvConfigUpperOutputVoltTolerance_instance, [1,3,6,1,4,1,318,1,1,1,5,2,37,0]).
-define(upsAdvConfigLowerOutputVoltTolerance, [1,3,6,1,4,1,318,1,1,1,5,2,38]).
-define(upsAdvConfigLowerOutputVoltTolerance_instance, [1,3,6,1,4,1,318,1,1,1,5,2,38,0]).
-define(upsAdvConfigUpperBypassVoltTolerance, [1,3,6,1,4,1,318,1,1,1,5,2,39]).
-define(upsAdvConfigUpperBypassVoltTolerance_instance, [1,3,6,1,4,1,318,1,1,1,5,2,39,0]).
-define(upsAdvConfigLowerBypassVoltTolerance, [1,3,6,1,4,1,318,1,1,1,5,2,40]).
-define(upsAdvConfigLowerBypassVoltTolerance_instance, [1,3,6,1,4,1,318,1,1,1,5,2,40,0]).
-define(upsAdvConfigOutofSyncBypassTransferDelay, [1,3,6,1,4,1,318,1,1,1,5,2,41]).
-define(upsAdvConfigOutofSyncBypassTransferDelay_instance, [1,3,6,1,4,1,318,1,1,1,5,2,41,0]).
-define(upsAdvConfigWarningAlarmDelay, [1,3,6,1,4,1,318,1,1,1,5,2,43]).
-define(upsAdvConfigWarningAlarmDelay_instance, [1,3,6,1,4,1,318,1,1,1,5,2,43,0]).
-define(upsAdvConfigInformationalAlarmDelay, [1,3,6,1,4,1,318,1,1,1,5,2,44]).
-define(upsAdvConfigInformationalAlarmDelay_instance, [1,3,6,1,4,1,318,1,1,1,5,2,44,0]).

-define(upsControl, [1,3,6,1,4,1,318,1,1,1,6]).

-define(upsBasicControl, [1,3,6,1,4,1,318,1,1,1,6,1]).
-define(upsBasicControlConserveBattery, [1,3,6,1,4,1,318,1,1,1,6,1,1]).
-define(upsBasicControlConserveBattery_instance, [1,3,6,1,4,1,318,1,1,1,6,1,1,0]).

-define(upsAdvControl, [1,3,6,1,4,1,318,1,1,1,6,2]).
-define(upsAdvControlUpsOff, [1,3,6,1,4,1,318,1,1,1,6,2,1]).
-define(upsAdvControlUpsOff_instance, [1,3,6,1,4,1,318,1,1,1,6,2,1,0]).
-define(upsAdvControlRebootShutdownUps, [1,3,6,1,4,1,318,1,1,1,6,2,2]).
-define(upsAdvControlRebootShutdownUps_instance, [1,3,6,1,4,1,318,1,1,1,6,2,2,0]).
-define(upsAdvControlUpsSleep, [1,3,6,1,4,1,318,1,1,1,6,2,3]).
-define(upsAdvControlUpsSleep_instance, [1,3,6,1,4,1,318,1,1,1,6,2,3,0]).
-define(upsAdvControlSimulatePowerFail, [1,3,6,1,4,1,318,1,1,1,6,2,4]).
-define(upsAdvControlSimulatePowerFail_instance, [1,3,6,1,4,1,318,1,1,1,6,2,4,0]).
-define(upsAdvControlFlashAndBeep, [1,3,6,1,4,1,318,1,1,1,6,2,5]).
-define(upsAdvControlFlashAndBeep_instance, [1,3,6,1,4,1,318,1,1,1,6,2,5,0]).
-define(upsAdvControlTurnOnUPS, [1,3,6,1,4,1,318,1,1,1,6,2,6]).
-define(upsAdvControlTurnOnUPS_instance, [1,3,6,1,4,1,318,1,1,1,6,2,6,0]).
-define(upsAdvControlBypassSwitch, [1,3,6,1,4,1,318,1,1,1,6,2,7]).
-define(upsAdvControlBypassSwitch_instance, [1,3,6,1,4,1,318,1,1,1,6,2,7,0]).
-define(upsAdvControlRebootUpsWithOrWithoutAC, [1,3,6,1,4,1,318,1,1,1,6,2,8]).
-define(upsAdvControlRebootUpsWithOrWithoutAC_instance, [1,3,6,1,4,1,318,1,1,1,6,2,8,0]).
-define(upsAdvControlFirmwareUpdate, [1,3,6,1,4,1,318,1,1,1,6,2,9]).
-define(upsAdvControlFirmwareUpdate_instance, [1,3,6,1,4,1,318,1,1,1,6,2,9,0]).

-define(upsTest, [1,3,6,1,4,1,318,1,1,1,7]).

-define(upsBasicTest, [1,3,6,1,4,1,318,1,1,1,7,1]).

-define(upsAdvTest, [1,3,6,1,4,1,318,1,1,1,7,2]).
-define(upsAdvTestDiagnosticSchedule, [1,3,6,1,4,1,318,1,1,1,7,2,1]).
-define(upsAdvTestDiagnosticSchedule_instance, [1,3,6,1,4,1,318,1,1,1,7,2,1,0]).
-define(upsAdvTestDiagnostics, [1,3,6,1,4,1,318,1,1,1,7,2,2]).
-define(upsAdvTestDiagnostics_instance, [1,3,6,1,4,1,318,1,1,1,7,2,2,0]).
-define(upsAdvTestDiagnosticsResults, [1,3,6,1,4,1,318,1,1,1,7,2,3]).
-define(upsAdvTestDiagnosticsResults_instance, [1,3,6,1,4,1,318,1,1,1,7,2,3,0]).
-define(upsAdvTestLastDiagnosticsDate, [1,3,6,1,4,1,318,1,1,1,7,2,4]).
-define(upsAdvTestLastDiagnosticsDate_instance, [1,3,6,1,4,1,318,1,1,1,7,2,4,0]).
-define(upsAdvTestRuntimeCalibration, [1,3,6,1,4,1,318,1,1,1,7,2,5]).
-define(upsAdvTestRuntimeCalibration_instance, [1,3,6,1,4,1,318,1,1,1,7,2,5,0]).
-define(upsAdvTestCalibrationResults, [1,3,6,1,4,1,318,1,1,1,7,2,6]).
-define(upsAdvTestCalibrationResults_instance, [1,3,6,1,4,1,318,1,1,1,7,2,6,0]).
-define(upsAdvTestCalibrationDate, [1,3,6,1,4,1,318,1,1,1,7,2,7]).
-define(upsAdvTestCalibrationDate_instance, [1,3,6,1,4,1,318,1,1,1,7,2,7,0]).
-define(upsAdvTestDiagnosticTime, [1,3,6,1,4,1,318,1,1,1,7,2,8]).
-define(upsAdvTestDiagnosticTime_instance, [1,3,6,1,4,1,318,1,1,1,7,2,8,0]).
-define(upsAdvTestDiagnosticDay, [1,3,6,1,4,1,318,1,1,1,7,2,9]).
-define(upsAdvTestDiagnosticDay_instance, [1,3,6,1,4,1,318,1,1,1,7,2,9,0]).

-define(upsComm, [1,3,6,1,4,1,318,1,1,1,8]).
-define(upsCommStatus, [1,3,6,1,4,1,318,1,1,1,8,1]).
-define(upsCommStatus_instance, [1,3,6,1,4,1,318,1,1,1,8,1,0]).

-define(upsPhase, [1,3,6,1,4,1,318,1,1,1,9]).

-define(upsPhaseResetValues, [1,3,6,1,4,1,318,1,1,1,9,1]).

-define(upsPhaseInput, [1,3,6,1,4,1,318,1,1,1,9,2]).

-define(upsPhaseOutput, [1,3,6,1,4,1,318,1,1,1,9,3]).

-define(upsSyncCtrlGroup, [1,3,6,1,4,1,318,1,1,1,10]).

-define(upsSyncCtrlGroupConfig, [1,3,6,1,4,1,318,1,1,1,10,1]).
-define(upsSCGMembershipGroupNumber, [1,3,6,1,4,1,318,1,1,1,10,1,1]).
-define(upsSCGMembershipGroupNumber_instance, [1,3,6,1,4,1,318,1,1,1,10,1,1,0]).
-define(upsSCGActiveMembershipStatus, [1,3,6,1,4,1,318,1,1,1,10,1,2]).
-define(upsSCGActiveMembershipStatus_instance, [1,3,6,1,4,1,318,1,1,1,10,1,2,0]).
-define(upsSCGPowerSynchronizationDelayTime, [1,3,6,1,4,1,318,1,1,1,10,1,3]).
-define(upsSCGPowerSynchronizationDelayTime_instance, [1,3,6,1,4,1,318,1,1,1,10,1,3,0]).
-define(upsSCGReturnBatteryCapacityOffset, [1,3,6,1,4,1,318,1,1,1,10,1,4]).
-define(upsSCGReturnBatteryCapacityOffset_instance, [1,3,6,1,4,1,318,1,1,1,10,1,4,0]).
-define(upsSCGMultiCastIP, [1,3,6,1,4,1,318,1,1,1,10,1,5]).
-define(upsSCGMultiCastIP_instance, [1,3,6,1,4,1,318,1,1,1,10,1,5,0]).

-define(upsSyncCtrlGroupStatus, [1,3,6,1,4,1,318,1,1,1,10,2]).
-define(upsSCGNumOfGroupMembers, [1,3,6,1,4,1,318,1,1,1,10,2,1]).
-define(upsSCGNumOfGroupMembers_instance, [1,3,6,1,4,1,318,1,1,1,10,2,1,0]).

-define(upsSCGStatusTable, [1,3,6,1,4,1,318,1,1,1,10,2,2]).

-define(upsSCGStatusEntry, [1,3,6,1,4,1,318,1,1,1,10,2,2,1]).
-define(upsSCGStatusTableIndex, 1).
-define(upsSCGMemberIP, 2).
-define(upsSCGACInputStatus, 3).
-define(upsSCGACOutputStatus, 4).

-define(upsState, [1,3,6,1,4,1,318,1,1,1,11]).

-define(upsBasicState, [1,3,6,1,4,1,318,1,1,1,11,1]).
-define(upsBasicStateOutputState, [1,3,6,1,4,1,318,1,1,1,11,1,1]).
-define(upsBasicStateOutputState_instance, [1,3,6,1,4,1,318,1,1,1,11,1,1,0]).

-define(upsAdvState, [1,3,6,1,4,1,318,1,1,1,11,2]).
-define(upsAdvStateAbnormalConditions, [1,3,6,1,4,1,318,1,1,1,11,2,1]).
-define(upsAdvStateAbnormalConditions_instance, [1,3,6,1,4,1,318,1,1,1,11,2,1,0]).
-define(upsAdvStateSymmetra3PhaseSpecificFaults, [1,3,6,1,4,1,318,1,1,1,11,2,2]).
-define(upsAdvStateSymmetra3PhaseSpecificFaults_instance, [1,3,6,1,4,1,318,1,1,1,11,2,2,0]).
-define(upsAdvStateDP300ESpecificFaults, [1,3,6,1,4,1,318,1,1,1,11,2,3]).
-define(upsAdvStateDP300ESpecificFaults_instance, [1,3,6,1,4,1,318,1,1,1,11,2,3,0]).
-define(upsAdvStateSymmetraSpecificFaults, [1,3,6,1,4,1,318,1,1,1,11,2,4]).
-define(upsAdvStateSymmetraSpecificFaults_instance, [1,3,6,1,4,1,318,1,1,1,11,2,4,0]).
-define(upsAdvStateSmartUPSSpecificFaults, [1,3,6,1,4,1,318,1,1,1,11,2,5]).
-define(upsAdvStateSmartUPSSpecificFaults_instance, [1,3,6,1,4,1,318,1,1,1,11,2,5,0]).
-define(upsAdvStateSystemMessages, [1,3,6,1,4,1,318,1,1,1,11,2,6]).
-define(upsAdvStateSystemMessages_instance, [1,3,6,1,4,1,318,1,1,1,11,2,6,0]).
-define(upsAdvStateTotaltimeonbattery, [1,3,6,1,4,1,318,1,1,1,11,2,7]).
-define(upsAdvStateTotaltimeonbattery_instance, [1,3,6,1,4,1,318,1,1,1,11,2,7,0]).
-define(upsAdvStateTotaltimeonbypass, [1,3,6,1,4,1,318,1,1,1,11,2,8]).
-define(upsAdvStateTotaltimeonbypass_instance, [1,3,6,1,4,1,318,1,1,1,11,2,8,0]).
-define(upsAdvStateTotaltimeonNormal, [1,3,6,1,4,1,318,1,1,1,11,2,9]).
-define(upsAdvStateTotaltimeonNormal_instance, [1,3,6,1,4,1,318,1,1,1,11,2,9,0]).
-define(upsAdvStateNumberoftimesonbattery, [1,3,6,1,4,1,318,1,1,1,11,2,10]).
-define(upsAdvStateNumberoftimesonbattery_instance, [1,3,6,1,4,1,318,1,1,1,11,2,10,0]).
-define(upsAdvStateNumberoftimesbypass, [1,3,6,1,4,1,318,1,1,1,11,2,11]).
-define(upsAdvStateNumberoftimesbypass_instance, [1,3,6,1,4,1,318,1,1,1,11,2,11,0]).
-define(upsAdvStateNumberoftimesNormal, [1,3,6,1,4,1,318,1,1,1,11,2,12]).
-define(upsAdvStateNumberoftimesNormal_instance, [1,3,6,1,4,1,318,1,1,1,11,2,12,0]).
-define(upsAdvStateEcomode, [1,3,6,1,4,1,318,1,1,1,11,2,13]).
-define(upsAdvStateEcomode_instance, [1,3,6,1,4,1,318,1,1,1,11,2,13,0]).

-define(upsOutletGroups, [1,3,6,1,4,1,318,1,1,1,12]).

-define(upsOutletGroupStatus, [1,3,6,1,4,1,318,1,1,1,12,1]).

-define(upsOutletGroupConfig, [1,3,6,1,4,1,318,1,1,1,12,2]).

-define(upsOutletGroupControl, [1,3,6,1,4,1,318,1,1,1,12,3]).

-define(upsDiagnostics, [1,3,6,1,4,1,318,1,1,1,13]).

-define(upsDiagnosticIM, [1,3,6,1,4,1,318,1,1,1,13,1]).

-define(upsDiagnosticPowerModules, [1,3,6,1,4,1,318,1,1,1,13,2]).

-define(upsDiagnosticBatteries, [1,3,6,1,4,1,318,1,1,1,13,3]).

-define(upsDiagnosticSubsystem, [1,3,6,1,4,1,318,1,1,1,13,4]).

-define(upsDiagnosticExternalDevices, [1,3,6,1,4,1,318,1,1,1,13,5]).

-define(upsDiagSwitchGear, [1,3,6,1,4,1,318,1,1,1,13,5,1]).

-define(upsDiagMCCBBox, [1,3,6,1,4,1,318,1,1,1,13,5,2]).

-define(upsDiagTransformer, [1,3,6,1,4,1,318,1,1,1,13,5,3]).

-define(upsDiagnosticComBus, [1,3,6,1,4,1,318,1,1,1,13,6]).

-define(upsParallelSystem, [1,3,6,1,4,1,318,1,1,1,14]).

-define(upsPhysicalLayout, [1,3,6,1,4,1,318,1,1,1,15]).

-define(upsIntegratedATS, [1,3,6,1,4,1,318,1,1,1,16]).

-define(measureUps, [1,3,6,1,4,1,318,1,1,2]).

-define(mUpsEnviron, [1,3,6,1,4,1,318,1,1,2,1]).
-define(mUpsEnvironAmbientTemperature, [1,3,6,1,4,1,318,1,1,2,1,1]).
-define(mUpsEnvironAmbientTemperature_instance, [1,3,6,1,4,1,318,1,1,2,1,1,0]).
-define(mUpsEnvironRelativeHumidity, [1,3,6,1,4,1,318,1,1,2,1,2]).
-define(mUpsEnvironRelativeHumidity_instance, [1,3,6,1,4,1,318,1,1,2,1,2,0]).
-define(mUpsEnvironAmbientTemperature2, [1,3,6,1,4,1,318,1,1,2,1,3]).
-define(mUpsEnvironAmbientTemperature2_instance, [1,3,6,1,4,1,318,1,1,2,1,3,0]).
-define(mUpsEnvironRelativeHumidity2, [1,3,6,1,4,1,318,1,1,2,1,4]).
-define(mUpsEnvironRelativeHumidity2_instance, [1,3,6,1,4,1,318,1,1,2,1,4,0]).

-define(mUpsContact, [1,3,6,1,4,1,318,1,1,2,2]).
-define(mUpsContactNumContacts, [1,3,6,1,4,1,318,1,1,2,2,1]).
-define(mUpsContactNumContacts_instance, [1,3,6,1,4,1,318,1,1,2,2,1,0]).

-define(mUpsContactTable, [1,3,6,1,4,1,318,1,1,2,2,2]).

-define(mUpsContactEntry, [1,3,6,1,4,1,318,1,1,2,2,2,1]).
-define(contactNumber, 1).
-define(normalState, 2).
-define(description, 3).
-define(monitoringStatus, 4).
-define(currentStatus, 5).


%% Range values
-define(low_upsAdvBatteryCapacity, 0).
-define(high_upsAdvBatteryCapacity, 4294967295).
-define(low_upsAdvBatteryTemperature, 0).
-define(high_upsAdvBatteryTemperature, 4294967295).
-define(low_upsHighPrecBatteryCapacity, 0).
-define(high_upsHighPrecBatteryCapacity, 4294967295).
-define(low_upsHighPrecBatteryTemperature, 0).
-define(high_upsHighPrecBatteryTemperature, 4294967295).
-define(low_upsAdvInputLineVoltage, 0).
-define(high_upsAdvInputLineVoltage, 4294967295).
-define(low_upsAdvInputMaxLineVoltage, 0).
-define(high_upsAdvInputMaxLineVoltage, 4294967295).
-define(low_upsAdvInputMinLineVoltage, 0).
-define(high_upsAdvInputMinLineVoltage, 4294967295).
-define(low_upsAdvInputFrequency, 0).
-define(high_upsAdvInputFrequency, 4294967295).
-define(low_upsHighPrecInputLineVoltage, 0).
-define(high_upsHighPrecInputLineVoltage, 4294967295).
-define(low_upsHighPrecInputMaxLineVoltage, 0).
-define(high_upsHighPrecInputMaxLineVoltage, 4294967295).
-define(low_upsHighPrecInputMinLineVoltage, 0).
-define(high_upsHighPrecInputMinLineVoltage, 4294967295).
-define(low_upsHighPrecInputFrequency, 0).
-define(high_upsHighPrecInputFrequency, 4294967295).
-define(low_upsAdvOutputVoltage, 0).
-define(high_upsAdvOutputVoltage, 4294967295).
-define(low_upsAdvOutputFrequency, 0).
-define(high_upsAdvOutputFrequency, 4294967295).
-define(low_upsAdvOutputLoad, 0).
-define(high_upsAdvOutputLoad, 4294967295).
-define(low_upsAdvOutputCurrent, 0).
-define(high_upsAdvOutputCurrent, 4294967295).
-define(low_upsAdvOutputRedundancy, 0).
-define(high_upsAdvOutputRedundancy, 4294967295).
-define(low_upsHighPrecOutputVoltage, 0).
-define(high_upsHighPrecOutputVoltage, 4294967295).
-define(low_upsHighPrecOutputFrequency, 0).
-define(high_upsHighPrecOutputFrequency, 4294967295).
-define(low_upsHighPrecOutputLoad, 0).
-define(high_upsHighPrecOutputLoad, 4294967295).
-define(low_upsHighPrecOutputCurrent, 0).
-define(high_upsHighPrecOutputCurrent, 4294967295).
-define(low_upsHighPrecOutputEfficiency, -2147483648).
-define(high_upsHighPrecOutputEfficiency, 2147483647).
-define(low_upsHighPrecOutputEnergyUsage, 0).
-define(high_upsHighPrecOutputEnergyUsage, 4294967295).
-define(low_upsAdvConfigUpperOutputVoltTolerance, 0).
-define(high_upsAdvConfigUpperOutputVoltTolerance, 100).
-define(low_upsAdvConfigLowerOutputVoltTolerance, 0).
-define(high_upsAdvConfigLowerOutputVoltTolerance, 100).
-define(low_upsAdvConfigUpperBypassVoltTolerance, 0).
-define(high_upsAdvConfigUpperBypassVoltTolerance, 100).
-define(low_upsAdvConfigLowerBypassVoltTolerance, 0).
-define(high_upsAdvConfigLowerBypassVoltTolerance, 100).
-define(low_mUpsEnvironAmbientTemperature, 0).
-define(high_mUpsEnvironAmbientTemperature, 4294967295).
-define(low_mUpsEnvironRelativeHumidity, 0).
-define(high_mUpsEnvironRelativeHumidity, 4294967295).
-define(low_mUpsEnvironAmbientTemperature2, 0).
-define(high_mUpsEnvironAmbientTemperature2, 4294967295).
-define(low_mUpsEnvironRelativeHumidity2, 0).
-define(high_mUpsEnvironRelativeHumidity2, 4294967295).


%% Enum definitions from upsBasicBatteryStatus
-define(upsBasicBatteryStatus_batteryLow, 3).
-define(upsBasicBatteryStatus_batteryNormal, 2).
-define(upsBasicBatteryStatus_unknown, 1).

%% Enum definitions from upsAdvBatteryReplaceIndicator
-define(upsAdvBatteryReplaceIndicator_batteryNeedsReplacing, 2).
-define(upsAdvBatteryReplaceIndicator_noBatteryNeedsReplacing, 1).

%% Enum definitions from upsAdvBatteryActualVoltagePolarity
-define(upsAdvBatteryActualVoltagePolarity_negative, 1).
-define(upsAdvBatteryActualVoltagePolarity_positive, 0).

%% Enum definitions from upsAdvTotalDCCurrentPolarity
-define(upsAdvTotalDCCurrentPolarity_negative, 1).
-define(upsAdvTotalDCCurrentPolarity_positive, 0).

%% Enum definitions from upsAdvBatteryCurrentPolarity
-define(upsAdvBatteryCurrentPolarity_negative, 1).
-define(upsAdvBatteryCurrentPolarity_positive, 0).

%% Enum definitions from upsHighPrecBatteryActualVoltagePolarity
-define(upsHighPrecBatteryActualVoltagePolarity_negative, 1).
-define(upsHighPrecBatteryActualVoltagePolarity_positive, 0).

%% Enum definitions from upsHighPrecTotalDCCurrentPolarity
-define(upsHighPrecTotalDCCurrentPolarity_negative, 1).
-define(upsHighPrecTotalDCCurrentPolarity_positive, 0).

%% Enum definitions from upsHighPrecBatteryCurrentPolarity
-define(upsHighPrecBatteryCurrentPolarity_negative, 1).
-define(upsHighPrecBatteryCurrentPolarity_positive, 0).

%% Enum definitions from upsAdvInputLineFailCause
-define(upsAdvInputLineFailCause_rateOfVoltageChange, 10).
-define(upsAdvInputLineFailCause_selfTest, 9).
-define(upsAdvInputLineFailCause_largeMomentarySpike, 8).
-define(upsAdvInputLineFailCause_smallMomentarySpike, 7).
-define(upsAdvInputLineFailCause_deepMomentarySag, 6).
-define(upsAdvInputLineFailCause_smallMomentarySag, 5).
-define(upsAdvInputLineFailCause_blackout, 4).
-define(upsAdvInputLineFailCause_brownout, 3).
-define(upsAdvInputLineFailCause_highLineVoltage, 2).
-define(upsAdvInputLineFailCause_noTransfer, 1).

%% Enum definitions from upsBasicOutputStatus
-define(upsBasicOutputStatus_onBatteryTest, 15).
-define(upsBasicOutputStatus_hotStandby, 14).
-define(upsBasicOutputStatus_ecoMode, 13).
-define(upsBasicOutputStatus_onSmartTrim, 12).
-define(upsBasicOutputStatus_sleepingUntilPowerReturn, 11).
-define(upsBasicOutputStatus_hardwareFailureBypass, 10).
-define(upsBasicOutputStatus_switchedBypass, 9).
-define(upsBasicOutputStatus_rebooting, 8).
-define(upsBasicOutputStatus_off, 7).
-define(upsBasicOutputStatus_softwareBypass, 6).
-define(upsBasicOutputStatus_timedSleeping, 5).
-define(upsBasicOutputStatus_onSmartBoost, 4).
-define(upsBasicOutputStatus_onBattery, 3).
-define(upsBasicOutputStatus_onLine, 2).
-define(upsBasicOutputStatus_unknown, 1).

%% Enum definitions from upsBasicSystemStatus
-define(upsBasicSystemStatus_ecoMode, 13).
-define(upsBasicSystemStatus_onSmartTrim, 12).
-define(upsBasicSystemStatus_sleepingUntilPowerReturn, 11).
-define(upsBasicSystemStatus_hardwareFailureBypass, 10).
-define(upsBasicSystemStatus_switchedBypass, 9).
-define(upsBasicSystemStatus_rebooting, 8).
-define(upsBasicSystemStatus_off, 7).
-define(upsBasicSystemStatus_softwareBypass, 6).
-define(upsBasicSystemStatus_timedSleeping, 5).
-define(upsBasicSystemStatus_onSmartBoost, 4).
-define(upsBasicSystemStatus_onBattery, 3).
-define(upsBasicSystemStatus_onLine, 2).
-define(upsBasicSystemStatus_unknown, 1).

%% Enum definitions from acceptThisDevice
-define(acceptThisDevice_no, 2).
-define(acceptThisDevice_yes, 1).

%% Enum definitions from upsAdvConfigAlarm
-define(upsAdvConfigAlarm_mute, 4).
-define(upsAdvConfigAlarm_never, 3).
-define(upsAdvConfigAlarm_atLowBattery, 2).
-define(upsAdvConfigAlarm_timed, 1).

%% Enum definitions from upsAdvConfigSensitivity
-define(upsAdvConfigSensitivity_high, 4).
-define(upsAdvConfigSensitivity_medium, 3).
-define(upsAdvConfigSensitivity_low, 2).
-define(upsAdvConfigSensitivity_auto, 1).

%% Enum definitions from upsAdvConfigSetEEPROMDefaults
-define(upsAdvConfigSetEEPROMDefaults_setEEPROMDefaults, 2).
-define(upsAdvConfigSetEEPROMDefaults_noSetEEPROMDefaults, 1).

%% Enum definitions from dipSwitchStatus
-define(dipSwitchStatus_off, 2).
-define(dipSwitchStatus_on, 1).

%% Enum definitions from upsAdvConfigPositionSelector
-define(upsAdvConfigPositionSelector_tower, 3).
-define(upsAdvConfigPositionSelector_rack, 2).
-define(upsAdvConfigPositionSelector_unknown, 1).

%% Enum definitions from upsAdvConfigOutputFreqRange
-define(upsAdvConfigOutputFreqRange_freqRange60Pct8, 22).
-define(upsAdvConfigOutputFreqRange_freqRange60Pct6, 21).
-define(upsAdvConfigOutputFreqRange_freqRange60Pct4, 20).
-define(upsAdvConfigOutputFreqRange_freqRange60Pct2, 19).
-define(upsAdvConfigOutputFreqRange_freqRange60Pct1, 18).
-define(upsAdvConfigOutputFreqRange_freqRange60Pct0dot5, 17).
-define(upsAdvConfigOutputFreqRange_freqRange50Pct8, 16).
-define(upsAdvConfigOutputFreqRange_freqRange50Pct6, 15).
-define(upsAdvConfigOutputFreqRange_freqRange50Pct4, 14).
-define(upsAdvConfigOutputFreqRange_freqRange50Pct2, 13).
-define(upsAdvConfigOutputFreqRange_freqRange50Pct1, 12).
-define(upsAdvConfigOutputFreqRange_freqRange50Pct0dot5, 11).
-define(upsAdvConfigOutputFreqRange_freqRange50Var1dot0, 10).
-define(upsAdvConfigOutputFreqRange_freqRange60Var1dot0, 9).
-define(upsAdvConfigOutputFreqRange_freqRange50Var10, 8).
-define(upsAdvConfigOutputFreqRange_freqRange60Var10, 7).
-define(upsAdvConfigOutputFreqRange_freqRange50Var3, 6).
-define(upsAdvConfigOutputFreqRange_freqRange50Var1, 5).
-define(upsAdvConfigOutputFreqRange_freqRange60Var3, 4).
-define(upsAdvConfigOutputFreqRange_freqRange60Var1, 3).
-define(upsAdvConfigOutputFreqRange_freqRangeAUTO, 2).
-define(upsAdvConfigOutputFreqRange_unknown, 1).

%% Enum definitions from upsAdvConfigUPSFail
-define(upsAdvConfigUPSFail_dropLoad, 3).
-define(upsAdvConfigUPSFail_gotoBypass, 2).
-define(upsAdvConfigUPSFail_unknown, 1).

%% Enum definitions from upsAdvConfigVoutReporting
-define(upsAdvConfigVoutReporting_vout240, 4).
-define(upsAdvConfigVoutReporting_vout208, 3).
-define(upsAdvConfigVoutReporting_voutAUTO, 2).
-define(upsAdvConfigVoutReporting_unknown, 1).

%% Enum definitions from upsAdvConfigSimpleSignalShutdowns
-define(upsAdvConfigSimpleSignalShutdowns_enabled, 3).
-define(upsAdvConfigSimpleSignalShutdowns_disabled, 2).
-define(upsAdvConfigSimpleSignalShutdowns_unknown, 1).

%% Enum definitions from upsAsiUpsControlServerRequestShutdown
-define(upsAsiUpsControlServerRequestShutdown_serverShutdownReboot, 2).
-define(upsAsiUpsControlServerRequestShutdown_serverShutdownOff, 1).

%% Enum definitions from upsAdvConfigBypassPhaseLockRequired
-define(upsAdvConfigBypassPhaseLockRequired_enabled, 3).
-define(upsAdvConfigBypassPhaseLockRequired_disabled, 2).
-define(upsAdvConfigBypassPhaseLockRequired_unknown, 1).

%% Enum definitions from upsAdvConfigOutputFreqSlewRate
-define(upsAdvConfigOutputFreqSlewRate_slewRate6HzPerSec, 7).
-define(upsAdvConfigOutputFreqSlewRate_slewRate4HzPerSec, 6).
-define(upsAdvConfigOutputFreqSlewRate_slewRate2HzPerSec, 5).
-define(upsAdvConfigOutputFreqSlewRate_slewRate1HzPerSec, 4).
-define(upsAdvConfigOutputFreqSlewRate_slewRateHalfHzPerSec, 3).
-define(upsAdvConfigOutputFreqSlewRate_slewRateQuarterHzPerSec, 2).
-define(upsAdvConfigOutputFreqSlewRate_unknown, 1).

%% Enum definitions from upsAdvConfigChargerLevel
-define(upsAdvConfigChargerLevel_high, 3).
-define(upsAdvConfigChargerLevel_low, 2).
-define(upsAdvConfigChargerLevel_unknown, 1).

%% Enum definitions from upsAdvConfigBypassToleranceSetting
-define(upsAdvConfigBypassToleranceSetting_custom, 5).
-define(upsAdvConfigBypassToleranceSetting_narrow, 4).
-define(upsAdvConfigBypassToleranceSetting_medium, 3).
-define(upsAdvConfigBypassToleranceSetting_wide, 2).
-define(upsAdvConfigBypassToleranceSetting_unknown, 1).

%% Enum definitions from upsAdvConfigMainsSetting
-define(upsAdvConfigMainsSetting_dualInput, 2).
-define(upsAdvConfigMainsSetting_singleInput, 1).

%% Enum definitions from upsAdvConfigACWiringSetting
-define(upsAdvConfigACWiringSetting_fourWire, 2).
-define(upsAdvConfigACWiringSetting_threeWire, 1).

%% Enum definitions from upsBasicControlConserveBattery
-define(upsBasicControlConserveBattery_turnOffUpsToConserveBattery, 2).
-define(upsBasicControlConserveBattery_noTurnOffUps, 1).

%% Enum definitions from upsAdvControlUpsOff
-define(upsAdvControlUpsOff_turnUpsSyncGroupOffGracefully, 6).
-define(upsAdvControlUpsOff_turnUpsSyncGroupOffAfterDelay, 5).
-define(upsAdvControlUpsOff_turnUpsSyncGroupOff, 4).
-define(upsAdvControlUpsOff_turnUpsOffGracefully, 3).
-define(upsAdvControlUpsOff_turnUpsOff, 2).
-define(upsAdvControlUpsOff_noTurnUpsOff, 1).

%% Enum definitions from upsAdvControlRebootShutdownUps
-define(upsAdvControlRebootShutdownUps_rebootShutdownSyncGroupUpsGracefully, 5).
-define(upsAdvControlRebootShutdownUps_rebootShutdownSyncGroupUps, 4).
-define(upsAdvControlRebootShutdownUps_rebootShutdownUpsGracefully, 3).
-define(upsAdvControlRebootShutdownUps_rebootShutdownUps, 2).
-define(upsAdvControlRebootShutdownUps_noRebootShutdownUps, 1).

%% Enum definitions from upsAdvControlUpsSleep
-define(upsAdvControlUpsSleep_putUpsSyncGroupToSleepGracefully, 5).
-define(upsAdvControlUpsSleep_putUpsSyncGroupToSleep, 4).
-define(upsAdvControlUpsSleep_putUpsToSleepGracefully, 3).
-define(upsAdvControlUpsSleep_putUpsToSleep, 2).
-define(upsAdvControlUpsSleep_noPutUpsToSleep, 1).

%% Enum definitions from upsAdvControlSimulatePowerFail
-define(upsAdvControlSimulatePowerFail_simulatePowerFailure, 2).
-define(upsAdvControlSimulatePowerFail_noSimulatePowerFailure, 1).

%% Enum definitions from upsAdvControlFlashAndBeep
-define(upsAdvControlFlashAndBeep_flashAndBeepCancel, 5).
-define(upsAdvControlFlashAndBeep_flashAndBeepCont, 4).
-define(upsAdvControlFlashAndBeep_flashAndBeepSyncGroup, 3).
-define(upsAdvControlFlashAndBeep_flashAndBeep, 2).
-define(upsAdvControlFlashAndBeep_noFlashAndBeep, 1).

%% Enum definitions from upsAdvControlTurnOnUPS
-define(upsAdvControlTurnOnUPS_turnOnUPSSyncGroup, 3).
-define(upsAdvControlTurnOnUPS_turnOnUPS, 2).
-define(upsAdvControlTurnOnUPS_noTurnOnUPS, 1).

%% Enum definitions from upsAdvControlBypassSwitch
-define(upsAdvControlBypassSwitch_switchOutOfBypass, 3).
-define(upsAdvControlBypassSwitch_switchToBypass, 2).
-define(upsAdvControlBypassSwitch_noBypassSwitch, 1).

%% Enum definitions from upsAdvControlRebootUpsWithOrWithoutAC
-define(upsAdvControlRebootUpsWithOrWithoutAC_rebootUpsDelayedWithOrWithoutAC, 3).
-define(upsAdvControlRebootUpsWithOrWithoutAC_rebootUpsImmediatelyWithOrWithoutAC, 2).
-define(upsAdvControlRebootUpsWithOrWithoutAC_noRebootUpsWithOrWithoutAC, 1).

%% Enum definitions from upsAdvControlFirmwareUpdate
-define(upsAdvControlFirmwareUpdate_updateFailed, 5).
-define(upsAdvControlFirmwareUpdate_updateSuccessful, 4).
-define(upsAdvControlFirmwareUpdate_updateInProcess, 3).
-define(upsAdvControlFirmwareUpdate_firmwareUpdate, 2).
-define(upsAdvControlFirmwareUpdate_noFirmwareUpdate, 1).

%% Enum definitions from upsAdvTestDiagnosticSchedule
-define(upsAdvTestDiagnosticSchedule_weeklySinceLastTest, 9).
-define(upsAdvTestDiagnosticSchedule_biweeklySinceLastTest, 8).
-define(upsAdvTestDiagnosticSchedule_twelveWeeks, 7).
-define(upsAdvTestDiagnosticSchedule_fourWeeks, 6).
-define(upsAdvTestDiagnosticSchedule_never, 5).
-define(upsAdvTestDiagnosticSchedule_atTurnOn, 4).
-define(upsAdvTestDiagnosticSchedule_weekly, 3).
-define(upsAdvTestDiagnosticSchedule_biweekly, 2).
-define(upsAdvTestDiagnosticSchedule_unknown, 1).

%% Enum definitions from upsAdvTestDiagnostics
-define(upsAdvTestDiagnostics_testDiagnostics, 2).
-define(upsAdvTestDiagnostics_noTestDiagnostics, 1).

%% Enum definitions from upsAdvTestDiagnosticsResults
-define(upsAdvTestDiagnosticsResults_testInProgress, 4).
-define(upsAdvTestDiagnosticsResults_invalidTest, 3).
-define(upsAdvTestDiagnosticsResults_failed, 2).
-define(upsAdvTestDiagnosticsResults_ok, 1).

%% Enum definitions from upsAdvTestRuntimeCalibration
-define(upsAdvTestRuntimeCalibration_cancelCurrentCalibration, 3).
-define(upsAdvTestRuntimeCalibration_performCalibration, 2).
-define(upsAdvTestRuntimeCalibration_noPerformCalibration, 1).

%% Enum definitions from upsAdvTestCalibrationResults
-define(upsAdvTestCalibrationResults_calibrationInProgress, 3).
-define(upsAdvTestCalibrationResults_invalidCalibration, 2).
-define(upsAdvTestCalibrationResults_ok, 1).

%% Enum definitions from upsAdvTestDiagnosticDay
-define(upsAdvTestDiagnosticDay_sunday, 7).
-define(upsAdvTestDiagnosticDay_saturday, 6).
-define(upsAdvTestDiagnosticDay_friday, 5).
-define(upsAdvTestDiagnosticDay_thursday, 4).
-define(upsAdvTestDiagnosticDay_wednesday, 3).
-define(upsAdvTestDiagnosticDay_tuesday, 2).
-define(upsAdvTestDiagnosticDay_monday, 1).

%% Enum definitions from upsCommStatus
-define(upsCommStatus_noComm, 2).
-define(upsCommStatus_ok, 1).

%% Enum definitions from upsSCGActiveMembershipStatus
-define(upsSCGActiveMembershipStatus_disabledSCG, 2).
-define(upsSCGActiveMembershipStatus_enabledSCG, 1).

%% Enum definitions from upsSCGACInputStatus
-define(upsSCGACInputStatus_acInBad, 2).
-define(upsSCGACInputStatus_acInGood, 1).

%% Enum definitions from upsSCGACOutputStatus
-define(upsSCGACOutputStatus_acOutOff, 2).
-define(upsSCGACOutputStatus_acOutOn, 1).

%% Enum definitions from upsAdvStateEcomode
-define(upsAdvStateEcomode_upsNotOnEcoMode, 2).
-define(upsAdvStateEcomode_upsOnEcoMode, 1).

%% Enum definitions from normalState
-define(normalState_closed, 3).
-define(normalState_open, 2).
-define(normalState_unknown, 1).

%% Enum definitions from monitoringStatus
-define(monitoringStatus_disabled, 3).
-define(monitoringStatus_enabled, 2).
-define(monitoringStatus_unknown, 1).

%% Enum definitions from currentStatus
-define(currentStatus_fault, 3).
-define(currentStatus_noFault, 2).
-define(currentStatus_unknown, 1).

%% Default values
-define(default_upsBasicIdentModel, []).
-define(default_upsBasicIdentName, []).
-define(default_upsAdvIdentFirmwareRevision, []).
-define(default_upsAdvIdentDateOfManufacture, []).
-define(default_upsAdvIdentSerialNumber, []).
-define(default_upsAdvIdentFirmwareRevision2, []).
-define(default_upsAdvIdentSkuNumber, []).
-define(default_upsBasicBatteryStatus, 1).
-define(default_upsBasicBatteryTimeOnBattery, 0).
-define(default_upsBasicBatteryLastReplaceDate, []).
-define(default_upsAdvBatteryCapacity, 0).
-define(default_upsAdvBatteryTemperature, 0).
-define(default_upsAdvBatteryRunTimeRemaining, 0).
-define(default_upsAdvBatteryReplaceIndicator, 1).
-define(default_upsAdvBatteryNumOfBattPacks, 0).
-define(default_upsAdvBatteryNumOfBadBattPacks, 0).
-define(default_upsAdvBatteryNominalVoltage, 0).
-define(default_upsAdvBatteryActualVoltage, 0).
-define(default_upsAdvBatteryCurrent, 0).
-define(default_upsAdvTotalDCCurrent, 0).
-define(default_upsAdvBatteryFullCapacity, 0).
-define(default_upsHighPrecBatteryCapacity, 0).
-define(default_upsHighPrecBatteryTemperature, 0).
-define(default_upsHighPrecBatteryNominalVoltage, 0).
-define(default_upsHighPrecBatteryActualVoltage, 0).
-define(default_upsHighPrecBatteryCurrent, 0).
-define(default_upsHighPrecTotalDCCurrent, 0).
-define(default_upsBasicInputPhase, 0).
-define(default_upsAdvInputLineVoltage, 0).
-define(default_upsAdvInputMaxLineVoltage, 0).
-define(default_upsAdvInputMinLineVoltage, 0).
-define(default_upsAdvInputFrequency, 0).
-define(default_upsAdvInputLineFailCause, 1).
-define(default_upsAdvInputNominalFrequency, 0).
-define(default_upsAdvInputNominalVoltage, 0).
-define(default_upsAdvInputBypassNominalFrequency, 0).
-define(default_upsAdvInputBypassNominalVoltage, 0).
-define(default_upsHighPrecInputLineVoltage, 0).
-define(default_upsHighPrecInputMaxLineVoltage, 0).
-define(default_upsHighPrecInputMinLineVoltage, 0).
-define(default_upsHighPrecInputFrequency, 0).
-define(default_upsBasicOutputStatus, 1).
-define(default_upsBasicOutputPhase, 0).
-define(default_upsBasicSystemStatus, 1).
-define(default_upsBasicSystemInternalTemperature, 0).
-define(default_upsAdvOutputVoltage, 0).
-define(default_upsAdvOutputFrequency, 0).
-define(default_upsAdvOutputLoad, 0).
-define(default_upsAdvOutputCurrent, 0).
-define(default_upsAdvOutputRedundancy, 0).
-define(default_upsAdvOutputKVACapacity, 0).
-define(default_upsAdvOutputNominalFrequency, 0).
-define(default_upsAdvOutputActivePower, 0).
-define(default_upsAdvOutputApparentPower, 0).
-define(default_upsHighPrecOutputVoltage, 0).
-define(default_upsHighPrecOutputFrequency, 0).
-define(default_upsHighPrecOutputLoad, 0).
-define(default_upsHighPrecOutputCurrent, 0).
-define(default_upsHighPrecOutputEfficiency, -2147483648).
-define(default_upsHighPrecOutputEnergyUsage, 0).
-define(default_upsBasicConfigNumDevices, 0).
-define(default_upsAdvConfigRatedOutputVoltage, 0).
-define(default_upsAdvConfigHighTransferVolt, 0).
-define(default_upsAdvConfigLowTransferVolt, 0).
-define(default_upsAdvConfigAlarm, 1).
-define(default_upsAdvConfigAlarmTimer, 0).
-define(default_upsAdvConfigMinReturnCapacity, 0).
-define(default_upsAdvConfigSensitivity, 1).
-define(default_upsAdvConfigLowBatteryRunTime, 0).
-define(default_upsAdvConfigReturnDelay, 0).
-define(default_upsAdvConfigShutoffDelay, 0).
-define(default_upsAdvConfigUpsSleepTime, 0).
-define(default_upsAdvConfigSetEEPROMDefaults, 1).
-define(default_upsAdvConfigBattExhaustThresh, 0).
-define(default_upsAdvConfigPassword, []).
-define(default_upsAdvConfigBattCabAmpHour, 0).
-define(default_upsAdvConfigPositionSelector, 1).
-define(default_upsAdvConfigOutputFreqRange, 1).
-define(default_upsAdvConfigUPSFail, 1).
-define(default_upsAdvConfigAlarmRedundancy, 0).
-define(default_upsAdvConfigAlarmLoadOver, 0).
-define(default_upsAdvConfigAlarmRuntimeUnder, 0).
-define(default_upsAdvConfigVoutReporting, 1).
-define(default_upsAdvConfigNumExternalBatteries, 0).
-define(default_upsAdvConfigSimpleSignalShutdowns, 1).
-define(default_upsAdvConfigMaxShutdownTime, 0).
-define(default_upsAsiUpsControlServerRequestShutdown, 1).
-define(default_upsAdvConfigMinReturnRuntime, 0).
-define(default_upsAdvConfigBasicSignalLowBatteryDuration, 0).
-define(default_upsAdvConfigBypassPhaseLockRequired, 1).
-define(default_upsAdvConfigOutputFreqSlewRate, 1).
-define(default_upsAdvConfigChargerLevel, 1).
-define(default_upsAdvConfigBypassToleranceSetting, 1).
-define(default_upsAdvConfigMainsSetting, 1).
-define(default_upsAdvConfigACWiringSetting, 1).
-define(default_upsAdvConfigUpperOutputVoltTolerance, 0).
-define(default_upsAdvConfigLowerOutputVoltTolerance, 0).
-define(default_upsAdvConfigUpperBypassVoltTolerance, 0).
-define(default_upsAdvConfigLowerBypassVoltTolerance, 0).
-define(default_upsAdvConfigOutofSyncBypassTransferDelay, 0).
-define(default_upsAdvConfigWarningAlarmDelay, 0).
-define(default_upsAdvConfigInformationalAlarmDelay, 0).
-define(default_upsBasicControlConserveBattery, 1).
-define(default_upsAdvControlUpsOff, 1).
-define(default_upsAdvControlRebootShutdownUps, 1).
-define(default_upsAdvControlUpsSleep, 1).
-define(default_upsAdvControlSimulatePowerFail, 1).
-define(default_upsAdvControlFlashAndBeep, 1).
-define(default_upsAdvControlTurnOnUPS, 1).
-define(default_upsAdvControlBypassSwitch, 1).
-define(default_upsAdvControlRebootUpsWithOrWithoutAC, 1).
-define(default_upsAdvControlFirmwareUpdate, 1).
-define(default_upsAdvTestDiagnosticSchedule, 1).
-define(default_upsAdvTestDiagnostics, 1).
-define(default_upsAdvTestDiagnosticsResults, 1).
-define(default_upsAdvTestLastDiagnosticsDate, []).
-define(default_upsAdvTestRuntimeCalibration, 1).
-define(default_upsAdvTestCalibrationResults, 1).
-define(default_upsAdvTestCalibrationDate, []).
-define(default_upsAdvTestDiagnosticTime, []).
-define(default_upsAdvTestDiagnosticDay, 1).
-define(default_upsCommStatus, 1).
-define(default_upsSCGMembershipGroupNumber, 0).
-define(default_upsSCGActiveMembershipStatus, 1).
-define(default_upsSCGPowerSynchronizationDelayTime, 0).
-define(default_upsSCGReturnBatteryCapacityOffset, 0).
-define(default_upsSCGMultiCastIP, [0,0,0,0]).
-define(default_upsSCGNumOfGroupMembers, 0).
-define(default_upsBasicStateOutputState, []).
-define(default_upsAdvStateAbnormalConditions, []).
-define(default_upsAdvStateSymmetra3PhaseSpecificFaults, []).
-define(default_upsAdvStateDP300ESpecificFaults, []).
-define(default_upsAdvStateSymmetraSpecificFaults, []).
-define(default_upsAdvStateSmartUPSSpecificFaults, []).
-define(default_upsAdvStateSystemMessages, []).
-define(default_upsAdvStateTotaltimeonbattery, []).
-define(default_upsAdvStateTotaltimeonbypass, []).
-define(default_upsAdvStateTotaltimeonNormal, []).
-define(default_upsAdvStateNumberoftimesonbattery, 0).
-define(default_upsAdvStateNumberoftimesbypass, 0).
-define(default_upsAdvStateNumberoftimesNormal, 0).
-define(default_upsAdvStateEcomode, 1).
-define(default_mUpsEnvironAmbientTemperature, 0).
-define(default_mUpsEnvironRelativeHumidity, 0).
-define(default_mUpsEnvironAmbientTemperature2, 0).
-define(default_mUpsEnvironRelativeHumidity2, 0).
-define(default_mUpsContactNumContacts, 0).

-endif.
