%%% This file was automatically generated by snmpc_mib_to_hrl version 4.22.1
%%% Date: 09-Nov-2012::01:43:26
-ifndef('WESTERMO-LYNX-MIB').
-define('WESTERMO-LYNX-MIB', true).

%% Notifications
-define(linkDownChangeWarning, [1,3,6,1,4,1,16177,1,2,7,4]).
-define(linkUpChangeWarning, [1,3,6,1,4,1,16177,1,2,7,3]).
-define(statNoWarning, [1,3,6,1,4,1,16177,1,2,7,2]).
-define(statWarning, [1,3,6,1,4,1,16177,1,2,7,1]).

%% Oids

-define(lynx, [1,3,6,1,4,1,16177,1,2]).

-define(general, [1,3,6,1,4,1,16177,1,2,1]).
-define(temperature, [1,3,6,1,4,1,16177,1,2,1,1]).
-define(temperature_instance, [1,3,6,1,4,1,16177,1,2,1,1,0]).
-define(swVersion, [1,3,6,1,4,1,16177,1,2,1,2]).
-define(swVersion_instance, [1,3,6,1,4,1,16177,1,2,1,2,0]).
-define(swVersionBootLoader, [1,3,6,1,4,1,16177,1,2,1,3]).
-define(swVersionBootLoader_instance, [1,3,6,1,4,1,16177,1,2,1,3,0]).
-define(hwVersionBoard, [1,3,6,1,4,1,16177,1,2,1,4]).
-define(hwVersionBoard_instance, [1,3,6,1,4,1,16177,1,2,1,4,0]).
-define(hwVersionPld, [1,3,6,1,4,1,16177,1,2,1,5]).
-define(hwVersionPld_instance, [1,3,6,1,4,1,16177,1,2,1,5,0]).
-define(serialNumber, [1,3,6,1,4,1,16177,1,2,1,6]).
-define(serialNumber_instance, [1,3,6,1,4,1,16177,1,2,1,6,0]).
-define(batchID, [1,3,6,1,4,1,16177,1,2,1,7]).
-define(batchID_instance, [1,3,6,1,4,1,16177,1,2,1,7,0]).
-define(hwConfig, [1,3,6,1,4,1,16177,1,2,1,8]).
-define(hwConfig_instance, [1,3,6,1,4,1,16177,1,2,1,8,0]).
-define(reset, [1,3,6,1,4,1,16177,1,2,1,9]).
-define(reset_instance, [1,3,6,1,4,1,16177,1,2,1,9,0]).
-define(powerSupply, [1,3,6,1,4,1,16177,1,2,1,10]).
-define(powerSupply_instance, [1,3,6,1,4,1,16177,1,2,1,10,0]).
-define(trapHostAddr1, [1,3,6,1,4,1,16177,1,2,1,11]).
-define(trapHostAddr1_instance, [1,3,6,1,4,1,16177,1,2,1,11,0]).
-define(trapHostAddr2, [1,3,6,1,4,1,16177,1,2,1,12]).
-define(trapHostAddr2_instance, [1,3,6,1,4,1,16177,1,2,1,12,0]).
-define(readPassword, [1,3,6,1,4,1,16177,1,2,1,13]).
-define(readPassword_instance, [1,3,6,1,4,1,16177,1,2,1,13,0]).
-define(writePassword, [1,3,6,1,4,1,16177,1,2,1,14]).
-define(writePassword_instance, [1,3,6,1,4,1,16177,1,2,1,14,0]).

-define(portGroup, [1,3,6,1,4,1,16177,1,2,1,15]).

-define(miscGroup, [1,3,6,1,4,1,16177,1,2,1,16]).

-define(trapGroup, [1,3,6,1,4,1,16177,1,2,1,17]).

-define(igmpGroup, [1,3,6,1,4,1,16177,1,2,1,18]).

-define(config, [1,3,6,1,4,1,16177,1,2,2]).
-define(ontPortNumber, [1,3,6,1,4,1,16177,1,2,2,1]).
-define(ontPortNumber_instance, [1,3,6,1,4,1,16177,1,2,2,1,0]).

-define(ontTable, [1,3,6,1,4,1,16177,1,2,2,2]).

-define(ontEntry, [1,3,6,1,4,1,16177,1,2,2,2,1]).
-define(portIndex, 1).
-define(portEnable, 2).
-define(portDuplexMode, 3).
-define(portAutoNegotiate, 4).
-define(portSpeed, 5).
-define(portAlarm, 6).
-define(portType, 7).
-define(timeSyncFilters, 8).
-define(rstpPortTrunk, 9).
-define(igmpPortTrunk, 10).
-define(removePortTag, 11).
-define(vlanId, 12).
-define(vlanPrio, 13).
-define(portVlanColors, 14).
-define(vlanDefaultColor, 15).
-define(igmpColor, 16).
-define(rstpPortStatus, 17).
-define(linkStatus, 18).
-define(snmp, [1,3,6,1,4,1,16177,1,2,2,3]).
-define(snmp_instance, [1,3,6,1,4,1,16177,1,2,2,3,0]).
-define(frnt, [1,3,6,1,4,1,16177,1,2,2,4]).
-define(frnt_instance, [1,3,6,1,4,1,16177,1,2,2,4,0]).
-define(frntPorts, [1,3,6,1,4,1,16177,1,2,2,5]).
-define(frntPorts_instance, [1,3,6,1,4,1,16177,1,2,2,5,0]).
-define(dhcp, [1,3,6,1,4,1,16177,1,2,2,6]).
-define(dhcp_instance, [1,3,6,1,4,1,16177,1,2,2,6,0]).
-define(enableVlan, [1,3,6,1,4,1,16177,1,2,2,7]).
-define(enableVlan_instance, [1,3,6,1,4,1,16177,1,2,2,7,0]).
-define(ipAddress, [1,3,6,1,4,1,16177,1,2,2,8]).
-define(ipAddress_instance, [1,3,6,1,4,1,16177,1,2,2,8,0]).
-define(ipNetMask, [1,3,6,1,4,1,16177,1,2,2,9]).
-define(ipNetMask_instance, [1,3,6,1,4,1,16177,1,2,2,9,0]).
-define(defaultGateway, [1,3,6,1,4,1,16177,1,2,2,10]).
-define(defaultGateway_instance, [1,3,6,1,4,1,16177,1,2,2,10,0]).
-define(dhcpRelayAgent, [1,3,6,1,4,1,16177,1,2,2,11]).
-define(dhcpRelayAgent_instance, [1,3,6,1,4,1,16177,1,2,2,11,0]).
-define(dhcpRelayAgentServer1, [1,3,6,1,4,1,16177,1,2,2,12]).
-define(dhcpRelayAgentServer1_instance, [1,3,6,1,4,1,16177,1,2,2,12,0]).
-define(dhcpRelayAgentServer2, [1,3,6,1,4,1,16177,1,2,2,13]).
-define(dhcpRelayAgentServer2_instance, [1,3,6,1,4,1,16177,1,2,2,13,0]).
-define(rstp, [1,3,6,1,4,1,16177,1,2,2,14]).
-define(rstp_instance, [1,3,6,1,4,1,16177,1,2,2,14,0]).

-define(igmp, [1,3,6,1,4,1,16177,1,2,5]).
-define(snooping, [1,3,6,1,4,1,16177,1,2,5,1]).
-define(snooping_instance, [1,3,6,1,4,1,16177,1,2,5,1,0]).
-define(automode, [1,3,6,1,4,1,16177,1,2,5,2]).
-define(automode_instance, [1,3,6,1,4,1,16177,1,2,5,2,0]).
-define(querier, [1,3,6,1,4,1,16177,1,2,5,3]).
-define(querier_instance, [1,3,6,1,4,1,16177,1,2,5,3,0]).
-define(stopfilter, [1,3,6,1,4,1,16177,1,2,5,4]).
-define(stopfilter_instance, [1,3,6,1,4,1,16177,1,2,5,4,0]).
-define(querytimeout, [1,3,6,1,4,1,16177,1,2,5,6]).
-define(querytimeout_instance, [1,3,6,1,4,1,16177,1,2,5,6,0]).

-define(stat, [1,3,6,1,4,1,16177,1,2,6]).
-define(statusCode, [1,3,6,1,4,1,16177,1,2,6,1]).
-define(statusCode_instance, [1,3,6,1,4,1,16177,1,2,6,1,0]).
-define(enableStatusTrap, [1,3,6,1,4,1,16177,1,2,6,2]).
-define(enableStatusTrap_instance, [1,3,6,1,4,1,16177,1,2,6,2,0]).

-define(privTraps, [1,3,6,1,4,1,16177,1,2,7]).


%% Range values
-define(low_temperature, -100).
-define(high_temperature, 100).
-define(low_swVersion, 0).
-define(high_swVersion, 255).
-define(low_swVersionBootLoader, 0).
-define(high_swVersionBootLoader, 255).
-define(low_hwVersionBoard, 0).
-define(high_hwVersionBoard, 255).
-define(low_hwVersionPld, 0).
-define(high_hwVersionPld, 255).
-define(low_serialNumber, 0).
-define(high_serialNumber, 255).
-define(low_batchID, 0).
-define(high_batchID, 255).
-define(low_trapHostAddr1, 0).
-define(high_trapHostAddr1, 255).
-define(low_trapHostAddr2, 0).
-define(high_trapHostAddr2, 255).
-define(low_readPassword, 0).
-define(high_readPassword, 255).
-define(low_writePassword, 0).
-define(high_writePassword, 255).
-define(low_ontPortNumber, 0).
-define(high_ontPortNumber, 64).
-define(low_portType, 0).
-define(high_portType, 255).
-define(low_vlanId, 0).
-define(high_vlanId, 4094).
-define(low_portVlanColors, 0).
-define(high_portVlanColors, 255).
-define(low_frntPorts, 0).
-define(high_frntPorts, 10).


%% Enum definitions from hwConfig
-define(hwConfig_intel, 23).
-define(hwConfig_amd, 22).

%% Enum definitions from reset
-define(reset_factoryDefault, 2).
-define(reset_reset, 1).

%% Enum definitions from powerSupply
-define(powerSupply_okpowerB, 3).
-define(powerSupply_okpowerA, 2).
-define(powerSupply_okpowerAB, 1).

%% Enum definitions from portIndex
-define(portIndex_port8, 8).
-define(portIndex_port7, 7).
-define(portIndex_port6, 6).
-define(portIndex_port5, 5).
-define(portIndex_port4, 4).
-define(portIndex_port3, 3).
-define(portIndex_port2, 2).
-define(portIndex_port1, 1).

%% Enum definitions from portEnable
-define(portEnable_disable, 3).
-define(portEnable_enable, 2).

%% Enum definitions from portDuplexMode
-define(portDuplexMode_full, 3).
-define(portDuplexMode_half, 2).

%% Enum definitions from portAutoNegotiate
-define(portAutoNegotiate_disable, 3).
-define(portAutoNegotiate_enable, 2).

%% Enum definitions from portSpeed
-define(portSpeed_s1000M, 1000).
-define(portSpeed_s100M, 100).
-define(portSpeed_s10M, 10).

%% Enum definitions from portAlarm
-define(portAlarm_disable, 2).
-define(portAlarm_enable, 1).

%% Enum definitions from timeSyncFilters
-define(timeSyncFilters_nonTiming, 1).
-define(timeSyncFilters_timing, 2).
-define(timeSyncFilters_unfiltered, 3).

%% Enum definitions from rstpPortTrunk
-define(rstpPortTrunk_disable, 2).
-define(rstpPortTrunk_enable, 1).

%% Enum definitions from igmpPortTrunk
-define(igmpPortTrunk_disable, 2).
-define(igmpPortTrunk_enable, 1).

%% Enum definitions from removePortTag
-define(removePortTag_removeTag, 2).
-define(removePortTag_keepTag, 1).

%% Enum definitions from vlanPrio
-define(vlanPrio_prio7, 7).
-define(vlanPrio_prio6, 6).
-define(vlanPrio_prio5, 5).
-define(vlanPrio_prio4, 4).
-define(vlanPrio_prio3, 3).
-define(vlanPrio_prio2, 2).
-define(vlanPrio_prio1, 1).
-define(vlanPrio_prio0, 0).

%% Enum definitions from vlanDefaultColor
-define(vlanDefaultColor_pink, 6).
-define(vlanDefaultColor_brown, 5).
-define(vlanDefaultColor_yellow, 4).
-define(vlanDefaultColor_green, 3).
-define(vlanDefaultColor_blue, 2).
-define(vlanDefaultColor_red, 1).
-define(vlanDefaultColor_white, 0).

%% Enum definitions from igmpColor
-define(igmpColor_red, 3).
-define(igmpColor_black, 1).

%% Enum definitions from rstpPortStatus
-define(rstpPortStatus_forwarding, 2).
-define(rstpPortStatus_discarding, 1).

%% Enum definitions from linkStatus
-define(linkStatus_down, 2).
-define(linkStatus_up, 1).

%% Enum definitions from snmp
-define(snmp_off, 3).
-define(snmp_on, 2).

%% Enum definitions from frnt
-define(frnt_member, 4).
-define(frnt_focalpoint, 3).
-define(frnt_disable, 2).

%% Enum definitions from dhcp
-define(dhcp_off, 3).
-define(dhcp_on, 2).

%% Enum definitions from enableVlan
-define(enableVlan_disable, 2).
-define(enableVlan_enable, 1).

%% Enum definitions from dhcpRelayAgent
-define(dhcpRelayAgent_off, 3).
-define(dhcpRelayAgent_on, 2).

%% Enum definitions from rstp
-define(rstp_off, 3).
-define(rstp_on, 2).
-define(rstp_root, 1).

%% Enum definitions from snooping
-define(snooping_off, 3).
-define(snooping_on, 2).

%% Enum definitions from automode
-define(automode_off, 3).
-define(automode_on, 2).

%% Enum definitions from querier
-define(querier_off, 3).
-define(querier_on, 2).

%% Enum definitions from stopfilter
-define(stopfilter_off, 3).
-define(stopfilter_on, 2).

%% Enum definitions from querytimeout
-define(querytimeout_t150s, 150).
-define(querytimeout_t70s, 70).
-define(querytimeout_t30s, 30).
-define(querytimeout_t12s, 12).

%% Enum definitions from statusCode
-define(statusCode_error, 2).
-define(statusCode_ok, 1).

%% Enum definitions from enableStatusTrap
-define(enableStatusTrap_off, 3).
-define(enableStatusTrap_on, 2).

%% Default values
-define(default_temperature, -100).
-define(default_swVersion, []).
-define(default_swVersionBootLoader, []).
-define(default_hwVersionBoard, []).
-define(default_hwVersionPld, []).
-define(default_serialNumber, []).
-define(default_batchID, []).
-define(default_hwConfig, 22).
-define(default_reset, 1).
-define(default_powerSupply, 1).
-define(default_trapHostAddr1, []).
-define(default_trapHostAddr2, []).
-define(default_readPassword, []).
-define(default_writePassword, []).
-define(default_ontPortNumber, 0).
-define(default_snmp, 2).
-define(default_frnt, 2).
-define(default_frntPorts, 0).
-define(default_dhcp, 2).
-define(default_enableVlan, 1).
-define(default_ipAddress, [0,0,0,0]).
-define(default_ipNetMask, [0,0,0,0]).
-define(default_defaultGateway, [0,0,0,0]).
-define(default_dhcpRelayAgent, 2).
-define(default_dhcpRelayAgentServer1, [0,0,0,0]).
-define(default_dhcpRelayAgentServer2, [0,0,0,0]).
-define(default_rstp, 1).
-define(default_snooping, 2).
-define(default_automode, 2).
-define(default_querier, 2).
-define(default_stopfilter, 2).
-define(default_querytimeout, 12).
-define(default_statusCode, 1).
-define(default_enableStatusTrap, 2).

-endif.
